name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *" # Runs every day at midnight
  workflow_dispatch: # Allows manual triggering

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      # Give the workflow write permissions to push changes
      contents: write
      
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # -- 👇 NEW STEP ADDED HERE 👇 --
      - name: Create output directory
        run: mkdir -p dist
      # -- 👆 NEW STEP ADDED HERE 👆 --

      - name: Generate Snake Animation
        uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          svg_out_path: dist/github-contribution-grid-snake.svg

      - name: Push to output branch
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
